name: Scope Maven JDK v1.8
on: [push]

jobs:
  scope:
    runs-on: ubuntu-latest
    steps:
      - name: Check if SCOPE_APIKEY is set
        run: if [ "${{secrets.SCOPE_DSN}}" = "" ]; then exit 1; fi
      - uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: Scope for Maven Action
        uses: undefinedlabs/scope-for-maven-action@v1
        with:
          dsn: ${{secrets.SCOPE_DSN}}
